# Configuration for cargo-deny
# https://github.com/EmbarkStudios/cargo-deny

[graph]
targets = [
    "x86_64-unknown-linux-gnu",
    "x86_64-apple-darwin",
    "x86_64-pc-windows-msvc",
    "wasm32-unknown-unknown",
]

[output]
feature-depth = 1

[advisories]
version = 2
db-path = "~/.cargo/advisory-db"
db-urls = ["https://github.com/rustsec/advisory-db"]
vulnerability = "deny"
unmaintained = "all"
yanked = "all"
notice = "all"
ignore = [
    #"RUSTSEC-0000-0000", # Example ignored advisory
]

[licenses]
version = 2
allow = [
    "MIT",
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "ISC",
    "Unicode-DFS-2016",
    "CC0-1.0",
    "0BSD",
    "Unlicense",
    "Zlib",
]
deny = [
    "GPL-2.0",
    "GPL-3.0",
    "AGPL-1.0",
    "AGPL-3.0",
]
copyleft = "warn"
allow-osi-fsf-free = "both"
default = "warn"
confidence-threshold = 0.8
exceptions = [
    # Example: { allow = ["GPL-3.0"], name = "some-gpl-crate" }
]

[licenses.private]
ignore = false
registries = []

[bans]
multiple-versions = "allow"
wildcards = "allow"
highlight = "all"
workspace-default-features = "allow"
external-default-features = "allow"
allow = [
    # Allow multiple versions of commonly duplicated crates
    { name = "base64" },
    { name = "der" },
    { name = "pkcs8" },
    { name = "signature" },
    { name = "spki" },
    { name = "syn" },
    { name = "windows-sys" },
    { name = "windows_aarch64_gnullvm" },
    { name = "windows_aarch64_msvc" },
    { name = "windows_i686_gnu" },
    { name = "windows_i686_msvc" },
    { name = "windows_x86_64_gnu" },
    { name = "windows_x86_64_gnullvm" },
    { name = "windows_x86_64_msvc" },
]
deny = [
    # Deny old versions with known vulnerabilities
    { name = "openssl", version = "<0.10.55" },
    { name = "openssl-sys", version = "<0.9.90" },
]
skip = [
]
skip-tree = [
]

[sources]
unknown-registry = "warn"
unknown-git = "warn"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []