# Configuration for cargo-deny
# https://github.com/EmbarkStudios/cargo-deny

[graph]
targets = [
    "x86_64-unknown-linux-gnu",
    "x86_64-apple-darwin",
    "x86_64-pc-windows-msvc",
    "wasm32-unknown-unknown",
]

[output]
feature-depth = 1

[advisories]
version = 2
db-path = "~/.cargo/advisory-db"
db-urls = ["https://github.com/rustsec/advisory-db"]
unmaintained = "all"
yanked = "warn"
ignore = [
    #"RUSTSEC-0000-0000", # Example ignored advisory
]

[licenses]
version = 2
allow = [
    "MIT",
    "Apache-2.0",
    "BSD-2-Clause", 
    "BSD-3-Clause",
    "Unicode-3.0",
    "Unicode-DFS-2016",
]
confidence-threshold = 0.6

[licenses.private]
ignore = false
registries = []

[bans]
multiple-versions = "allow"
wildcards = "allow"
workspace-default-features = "allow"
external-default-features = "allow"
allow = [
    # Allow multiple versions of commonly duplicated crates
    { name = "base64" },
    { name = "der" },
    { name = "pkcs8" },
    { name = "signature" },
    { name = "spki" },
    { name = "syn" },
    { name = "windows-sys" },
    { name = "windows_aarch64_gnullvm" },
    { name = "windows_aarch64_msvc" },
    { name = "windows_i686_gnu" },
    { name = "windows_i686_msvc" },
    { name = "windows_x86_64_gnu" },
    { name = "windows_x86_64_gnullvm" },
    { name = "windows_x86_64_msvc" },
]
skip = [
]
skip-tree = [
]

[sources]
unknown-registry = "allow"
unknown-git = "allow"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []