/* SAGE crypto core C API. Every function is documented in src/ffi. */

#ifndef SAGE_CRYPTO_H
#define SAGE_CRYPTO_H

/* Generated with cbindgen:0.29.4 */

/* Generated by cbindgen from src/ffi; do not edit. Regenerate with `make header`. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Maximum number of keys allowed per agent
 */
#define MAX_KEYS_PER_AGENT 10

/**
 * Size of the sequence header.
 */
#define SEQ_SIZE 8

/**
 * Size of the nonce.
 */
#define NONCE_SIZE 12

/**
 * Size of the record header (`seq || nonce`).
 */
#define HEADER_SIZE (SEQ_SIZE + NONCE_SIZE)

/**
 * Replay window size in records.
 */
#define REPLAY_WINDOW_SIZE 1024

/**
 * Default number of records per direction after which the AEAD key rotates.
 */
#define DEFAULT_REKEY_INTERVAL 256

/**
 * Key format enum for FFI
 */
typedef enum SageKeyFormat {
  /**
   * Raw binary format
   */
  SAGE_KEY_FORMAT_RAW = 0,
  /**
   * PEM format
   */
  SAGE_KEY_FORMAT_PEM = 1,
  /**
   * DER format
   */
  SAGE_KEY_FORMAT_DER = 2,
  /**
   * JWK format
   */
  SAGE_KEY_FORMAT_JWK = 3,
} SageKeyFormat;

/**
 * Key type enum for FFI
 */
typedef enum SageKeyType {
  /**
   * Ed25519 key type
   */
  SAGE_KEY_TYPE_ED25519 = 0,
  /**
   * Secp256k1 key type
   */
  SAGE_KEY_TYPE_SECP256K1 = 1,
  /**
   * P-256 key type
   */
  SAGE_KEY_TYPE_P256 = 2,
} SageKeyType;

/**
 * Error codes for FFI
 */
typedef enum SageErrorCode {
  /**
   * Success
   */
  SAGE_ERROR_CODE_SUCCESS = 0,
  /**
   * Invalid input parameter
   */
  SAGE_ERROR_CODE_INVALID_INPUT = 1,
  /**
   * Cryptographic operation failed
   */
  SAGE_ERROR_CODE_CRYPTO_ERROR = 2,
  /**
   * Memory allocation failed
   */
  SAGE_ERROR_CODE_ALLOCATION_ERROR = 3,
  /**
   * Unsupported operation
   */
  SAGE_ERROR_CODE_UNSUPPORTED = 4,
  /**
   * Verification failed
   */
  SAGE_ERROR_CODE_VERIFICATION_FAILED = 5,
  /**
   * Unknown error
   */
  SAGE_ERROR_CODE_UNKNOWN_ERROR = 99,
} SageErrorCode;

/**
 * Opaque handle for HTTP signer
 */
typedef struct SageHttpSigner SageHttpSigner;

/**
 * Opaque handle for HTTP verifier
 */
typedef struct SageHttpVerifier SageHttpVerifier;

/**
 * Opaque handle for KeyPair
 */
typedef struct SageKeyPair SageKeyPair;

/**
 * Opaque handle for PublicKey
 */
typedef struct SagePublicKey SagePublicKey;

/**
 * Opaque handle for a session
 */
typedef struct SageSession SageSession;

/**
 * Opaque handle for Signature
 */
typedef struct SageSignature SageSignature;

/**
 * Validation limits for input data
 */
typedef struct ValidationLimits ValidationLimits;

/**
 * Result type for FFI functions
 */
typedef int SageResult;

/**
 * HTTP header (name, value) for FFI
 */
typedef struct SageHttpHeader {
  /**
   * Header name
   */
  const char *name;
  /**
   * Header value
   */
  const char *value;
} SageHttpHeader;

/**
 * HTTP request view for FFI
 */
typedef struct SageHttpRequest {
  /**
   * Method (`POST`)
   */
  const char *method;
  /**
   * Absolute target URI
   */
  const char *uri;
  /**
   * Headers
   */
  const struct SageHttpHeader *headers;
  /**
   * Number of headers
   */
  size_t headers_count;
  /**
   * Body bytes (may be NULL)
   */
  const unsigned char *body;
  /**
   * Body length
   */
  size_t body_len;
} SageHttpRequest;

/**
 * HTTP response view for FFI
 */
typedef struct SageHttpResponse {
  /**
   * Status code
   */
  int status;
  /**
   * Headers
   */
  const struct SageHttpHeader *headers;
  /**
   * Number of headers
   */
  size_t headers_count;
  /**
   * Body bytes (may be NULL)
   */
  const unsigned char *body;
  /**
   * Body length
   */
  size_t body_len;
} SageHttpResponse;

/**
 * Verification policy for FFI. `strict` enables the sage-spec strict
 * request or response policy; `max_age_secs < 0` disables the age check;
 * `expected_did` may be NULL.
 */
typedef struct SageVerifyOptions {
  /**
   * Non-zero for the strict policy
   */
  int strict;
  /**
   * Maximum signature age in seconds; negative disables the check
   */
  int64_t max_age_secs;
  /**
   * DID the `keyid` must carry (NULL to skip)
   */
  const char *expected_did;
  /**
   * Non-zero to skip the replay check
   */
  int disable_replay_check;
} SageVerifyOptions;







#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Initialize the library (currently no-op, reserved for future use)
 */
SageResult sage_init(void);

/**
 * Get the version string of the library
 */
const char *sage_version(void);

/**
 * Get the last error message (thread-local)
 */
const char *sage_last_error(void);

/**
 * Clear the last error message
 */
void sage_clear_error(void);

/**
 * Export a key pair to a specific format
 *
 * # Safety
 * The caller must ensure that:
 * - `keypair` is a valid pointer
 * - `format` is a valid format
 * - `out_data` is a valid pointer with sufficient space
 * - `out_len` is a valid pointer
 */
SageResult sage_keypair_export_format(const struct SageKeyPair *keypair,
                                      enum SageKeyFormat format,
                                      unsigned char *out_data,
                                      size_t *out_len);

/**
 * Import a key pair from a specific format
 *
 * # Safety
 * The caller must ensure that:
 * - `key_type` is a valid key type
 * - `format` is a valid format
 * - `data` is a valid pointer to the key data
 * - `data_len` is the correct length
 * - `out_keypair` is a valid pointer to a `*mut SageKeyPair`
 */
SageResult sage_keypair_import_format(enum SageKeyType key_type,
                                      enum SageKeyFormat format,
                                      const unsigned char *data,
                                      size_t data_len,
                                      struct SageKeyPair **out_keypair);

/**
 * Export a public key to a specific format
 *
 * # Safety
 * The caller must ensure that:
 * - `public_key` is a valid pointer
 * - `format` is a valid format
 * - `out_data` is a valid pointer with sufficient space
 * - `out_len` is a valid pointer
 */
SageResult sage_public_key_export_format(const struct SagePublicKey *public_key,
                                         enum SageKeyFormat format,
                                         unsigned char *out_data,
                                         size_t *out_len);

/**
 * Import a public key from a specific format
 *
 * # Safety
 * The caller must ensure that:
 * - `key_type` is a valid key type
 * - `format` is a valid format
 * - `data` is a valid pointer to the key data
 * - `data_len` is the correct length
 * - `out_public_key` is a valid pointer to a `*mut SagePublicKey`
 */
SageResult sage_public_key_import_format(enum SageKeyType key_type,
                                         enum SageKeyFormat format,
                                         const unsigned char *data,
                                         size_t data_len,
                                         struct SagePublicKey **out_public_key);

/**
 * Export a key pair to PEM format (convenience function)
 *
 * # Safety
 * The caller must ensure that:
 * - `keypair` is a valid pointer
 * - `out_pem` is a valid pointer to receive the PEM string
 */
SageResult sage_keypair_to_pem(const struct SageKeyPair *keypair, char **out_pem);

/**
 * Import a key pair from PEM format (convenience function)
 *
 * # Safety
 * The caller must ensure that:
 * - `key_type` is a valid key type
 * - `pem_data` is a valid null-terminated string
 * - `out_keypair` is a valid pointer to a `*mut SageKeyPair`
 */
SageResult sage_keypair_from_pem(enum SageKeyType key_type,
                                 const char *pem_data,
                                 struct SageKeyPair **out_keypair);

/**
 * Export a public key to PEM format (convenience function)
 *
 * # Safety
 * The caller must ensure that:
 * - `public_key` is a valid pointer
 * - `out_pem` is a valid pointer to receive the PEM string
 */
SageResult sage_public_key_to_pem(const struct SagePublicKey *public_key, char **out_pem);

/**
 * Import a public key from PEM format (convenience function)
 *
 * # Safety
 * The caller must ensure that:
 * - `key_type` is a valid key type
 * - `pem_data` is a valid null-terminated string
 * - `out_public_key` is a valid pointer to a `*mut SagePublicKey`
 */
SageResult sage_public_key_from_pem(enum SageKeyType key_type,
                                    const char *pem_data,
                                    struct SagePublicKey **out_public_key);

/**
 * Create a new HTTP signer. The `keyid` parameter defaults to the key id;
 * set the agent DID with `sage_http_signer_set_key_id`.
 *
 * # Safety
 * `keypair` and `out_signer` must be valid pointers.
 */
SageResult sage_http_signer_new(const struct SageKeyPair *keypair,
                                struct SageHttpSigner **out_signer);

/**
 * Set the `keyid` parameter (`did:sage:…` or `did:sage:…#key-1`).
 *
 * # Safety
 * `signer` must be a valid signer and `key_id` a NUL-terminated string.
 */
SageResult sage_http_signer_set_key_id(struct SageHttpSigner *signer, const char *key_id);

/**
 * Free an HTTP signer
 *
 * # Safety
 * `signer` must have been returned by `sage_http_signer_new` or be NULL.
 */
void sage_http_signer_free(struct SageHttpSigner *signer);

/**
 * Sign a request with the sage-spec default components. Returns the
 * headers to add (`content-digest` when a body was given,
 * `signature-input`, `signature`). On a too-small buffer the required
 * count is written to `out_headers_count` and `InvalidInput` returned.
 *
 * # Safety
 * All pointers must be valid; `out_signed_headers` must have room for
 * `*out_headers_count` entries.
 */
SageResult sage_http_signer_sign_request(const struct SageHttpSigner *signer,
                                         const struct SageHttpRequest *request,
                                         struct SageHttpHeader *out_signed_headers,
                                         size_t *out_headers_count);

/**
 * Sign a response bound to the request it answers (reference responder
 * component set). Returns the headers to add to the response.
 *
 * # Safety
 * All pointers must be valid; `out_signed_headers` must have room for
 * `*out_headers_count` entries.
 */
SageResult sage_http_signer_sign_response(const struct SageHttpSigner *signer,
                                          const struct SageHttpRequest *request,
                                          const struct SageHttpResponse *response,
                                          struct SageHttpHeader *out_signed_headers,
                                          size_t *out_headers_count);

/**
 * Create a new HTTP verifier for `public_key` (with an in-memory replay guard).
 *
 * # Safety
 * `public_key` and `out_verifier` must be valid pointers.
 */
SageResult sage_http_verifier_new(const struct SagePublicKey *public_key,
                                  struct SageHttpVerifier **out_verifier);

/**
 * Free an HTTP verifier
 *
 * # Safety
 * `verifier` must have been returned by `sage_http_verifier_new` or be NULL.
 */
void sage_http_verifier_free(struct SageHttpVerifier *verifier);

/**
 * Verify a request with the default options (see
 * `sage_http_verifier_verify_request_with` for the strict policy).
 *
 * # Safety
 * `verifier` and `request` must be valid pointers.
 */
SageResult sage_http_verifier_verify_request(const struct SageHttpVerifier *verifier,
                                             const struct SageHttpRequest *request);

/**
 * Verify a request with explicit options. The body of `request` is
 * checked against `Content-Digest` when it is covered.
 *
 * # Safety
 * `verifier` and `request` must be valid; `options` may be NULL.
 */
SageResult sage_http_verifier_verify_request_with(const struct SageHttpVerifier *verifier,
                                                  const struct SageHttpRequest *request,
                                                  const struct SageVerifyOptions *options);

/**
 * Verify a response against the request it answers.
 *
 * # Safety
 * `verifier`, `request` and `response` must be valid; `options` may be NULL.
 */
SageResult sage_http_verifier_verify_response(const struct SageHttpVerifier *verifier,
                                              const struct SageHttpRequest *request,
                                              const struct SageHttpResponse *response,
                                              const struct SageVerifyOptions *options);

/**
 * Free headers returned by the signing functions.
 *
 * # Safety
 * `headers` must point to `count` entries whose strings were allocated by
 * this library.
 */
void sage_http_headers_free(struct SageHttpHeader *headers, size_t count);

/**
 * Generate a new key pair
 *
 * # Safety
 * The caller must ensure that `out_keypair` is a valid pointer to a `*mut SageKeyPair`.
 */
SageResult sage_keypair_generate(enum SageKeyType key_type, struct SageKeyPair **out_keypair);

/**
 * Free a key pair
 *
 * # Safety
 * The caller must ensure that `keypair` is a valid pointer obtained from `sage_keypair_generate`.
 */
void sage_keypair_free(struct SageKeyPair *keypair);

/**
 * Get the public key from a key pair
 *
 * # Safety
 * The caller must ensure that:
 * - `keypair` is a valid pointer
 * - `out_public_key` is a valid pointer to a `*mut SagePublicKey`
 */
SageResult sage_keypair_get_public_key(const struct SageKeyPair *keypair,
                                       struct SagePublicKey **out_public_key);

/**
 * Get the key ID from a key pair
 *
 * # Safety
 * The caller must ensure that:
 * - `keypair` is a valid pointer
 * - `out_key_id` is a valid pointer with sufficient space (at least 64 bytes)
 * - `out_len` is a valid pointer
 */
SageResult sage_keypair_get_key_id(const struct SageKeyPair *keypair,
                                   char *out_key_id,
                                   size_t *out_len);

/**
 * Get the key type from a key pair
 *
 * # Safety
 * The caller must ensure that `keypair` is a valid pointer.
 */
enum SageKeyType sage_keypair_get_type(const struct SageKeyPair *keypair);

/**
 * Export a key pair to bytes
 *
 * # Safety
 * The caller must ensure that:
 * - `keypair` is a valid pointer
 * - `out_private_key` is a valid pointer with sufficient space (32 bytes)
 * - `private_key_len` is a valid pointer
 * - `out_public_key` is a valid pointer with sufficient space (32-33 bytes)
 * - `public_key_len` is a valid pointer
 */
SageResult sage_keypair_export(const struct SageKeyPair *keypair,
                               unsigned char *out_private_key,
                               size_t *private_key_len,
                               unsigned char *out_public_key,
                               size_t *public_key_len);

/**
 * Import a key pair from bytes
 *
 * # Safety
 * The caller must ensure that:
 * - `key_type` is a valid key type
 * - `private_key` is a valid pointer to private key bytes
 * - `private_key_len` is the correct length for the key type
 * - `out_keypair` is a valid pointer to a `*mut SageKeyPair`
 */
SageResult sage_keypair_import(enum SageKeyType key_type,
                               const unsigned char *private_key,
                               size_t private_key_len,
                               struct SageKeyPair **out_keypair);

/**
 * Sign a message
 *
 * # Safety
 * The caller must ensure that:
 * - `keypair` is a valid pointer
 * - `message` is a valid pointer to message bytes
 * - `message_len` is the correct length
 * - `out_signature` is a valid pointer to a `*mut SageSignature`
 */
SageResult sage_sign(const struct SageKeyPair *keypair,
                     const unsigned char *message,
                     size_t message_len,
                     struct SageSignature **out_signature);

/**
 * Verify a signature with a key pair
 *
 * # Safety
 * The caller must ensure that:
 * - `keypair` is a valid pointer
 * - `message` is a valid pointer to message bytes
 * - `message_len` is the correct length
 * - `signature` is a valid pointer
 */
SageResult sage_verify_with_keypair(const struct SageKeyPair *keypair,
                                    const unsigned char *message,
                                    size_t message_len,
                                    const struct SageSignature *signature);

/**
 * Verify a signature with a public key
 *
 * # Safety
 * The caller must ensure that:
 * - `public_key` is a valid pointer
 * - `message` is a valid pointer to message bytes
 * - `message_len` is the correct length
 * - `signature` is a valid pointer
 */
SageResult sage_verify_with_public_key(const struct SagePublicKey *public_key,
                                       const unsigned char *message,
                                       size_t message_len,
                                       const struct SageSignature *signature);

/**
 * Free a signature
 *
 * # Safety
 * The caller must ensure that `signature` is a valid pointer obtained from `sage_sign`.
 */
void sage_signature_free(struct SageSignature *signature);

/**
 * Export a signature to bytes
 *
 * # Safety
 * The caller must ensure that:
 * - `signature` is a valid pointer
 * - `out_bytes` is a valid pointer with sufficient space (up to 72 bytes for DER-encoded signatures)
 * - `out_len` is a valid pointer
 */
SageResult sage_signature_export(const struct SageSignature *signature,
                                 unsigned char *out_bytes,
                                 size_t *out_len);

/**
 * Free a public key
 *
 * # Safety
 * The caller must ensure that `public_key` is a valid pointer.
 */
void sage_public_key_free(struct SagePublicKey *public_key);

/**
 * Export a public key to bytes
 *
 * # Safety
 * The caller must ensure that:
 * - `public_key` is a valid pointer
 * - `out_bytes` is a valid pointer with sufficient space (32-33 bytes)
 * - `out_len` is a valid pointer
 */
SageResult sage_public_key_export(const struct SagePublicKey *public_key,
                                  unsigned char *out_bytes,
                                  size_t *out_len);

/**
 * Import a public key from bytes
 *
 * # Safety
 * The caller must ensure that:
 * - `key_type` is a valid key type
 * - `bytes` is a valid pointer to public key bytes
 * - `bytes_len` is the correct length for the key type
 * - `out_public_key` is a valid pointer to a `*mut SagePublicKey`
 */
SageResult sage_public_key_import(enum SageKeyType key_type,
                                  const unsigned char *bytes,
                                  size_t bytes_len,
                                  struct SagePublicKey **out_public_key);

/**
 * Canonicalise JSON (RFC 8785).
 *
 * # Safety
 * `input` must point to `input_len` bytes; `out`/`out_len` follow the buffer convention.
 */
SageResult sage_jcs_canonicalize(const unsigned char *input_ptr,
                                 size_t input_len,
                                 unsigned char *out,
                                 size_t *out_len);

/**
 * Whether `did` is a well-formed `did:sage:<chain>:<identifier>`.
 *
 * # Safety
 * `did` must be a NUL-terminated string.
 */
SageResult sage_did_validate(const char *did);

/**
 * Generate the key proof of possession of `keypair` for `did`
 * (64 bytes Ed25519, 65 bytes secp256k1).
 *
 * # Safety
 * `keypair` must be valid; `did` NUL-terminated; buffer convention for `out`.
 */
SageResult sage_key_pop_generate(const struct SageKeyPair *keypair,
                                 const char *did,
                                 unsigned char *out,
                                 size_t *out_len);

/**
 * Verify a key proof of possession.
 *
 * # Safety
 * `key_data` and `proof` must point to their lengths; `did` NUL-terminated.
 */
SageResult sage_key_pop_verify(enum SageKeyType key_type,
                               const unsigned char *key_data,
                               size_t key_len,
                               const char *did,
                               const unsigned char *proof,
                               size_t proof_len);

/**
 * Parse an A2A agent card and verify its proof.
 *
 * # Safety
 * `json` must point to `json_len` bytes.
 */
SageResult sage_a2a_card_verify(const unsigned char *json, size_t json_len);

/**
 * Session id for a seed and label (`base64url(SHA-256(label || seed)[0:16])`).
 *
 * # Safety
 * `seed` must point to `seed_len` bytes; `label` NUL-terminated; buffer convention for `out`.
 */
SageResult sage_session_id_from_seed(const unsigned char *seed,
                                     size_t seed_len,
                                     const char *label,
                                     unsigned char *out,
                                     size_t *out_len);

/**
 * Create a session. `role` is 1 for the initiator, 0 for the responder and
 * -1 for a session without a role (shared keys only). `rekey_interval` 0
 * disables key rotation; 256 is the default.
 *
 * # Safety
 * `session_id` NUL-terminated; `seed` must point to `seed_len` bytes; `out` valid.
 */
SageResult sage_session_new(const char *session_id,
                            const unsigned char *seed,
                            size_t seed_len,
                            int role,
                            uint64_t rekey_interval,
                            struct SageSession **out);

/**
 * Free a session
 *
 * # Safety
 * `session` must have been returned by `sage_session_new` or be NULL.
 */
void sage_session_free(struct SageSession *session);

/**
 * Encrypt a record (outbound direction for role sessions). `aad` may be NULL.
 *
 * # Safety
 * Pointers must be valid; buffer convention for `out`.
 */
SageResult sage_session_encrypt(const struct SageSession *session,
                                const unsigned char *plaintext,
                                size_t plaintext_len,
                                const unsigned char *aad,
                                size_t aad_len,
                                unsigned char *out,
                                size_t *out_len);

/**
 * Decrypt a record (inbound direction for role sessions). `aad` may be NULL.
 *
 * # Safety
 * Pointers must be valid; buffer convention for `out`.
 */
SageResult sage_session_decrypt(const struct SageSession *session,
                                const unsigned char *record,
                                size_t record_len,
                                const unsigned char *aad,
                                size_t aad_len,
                                unsigned char *out,
                                size_t *out_len);

/**
 * Records sent plus received.
 *
 * # Safety
 * `session` must be valid.
 */
size_t sage_session_message_count(const struct SageSession *session);

/**
 * Free a C string allocated by this library
 *
 * # Safety
 * The caller must ensure that `str` is a valid pointer allocated by this library.
 */
void sage_string_free(char *str);

/**
 * Generate a random nonce
 *
 * # Safety
 * The caller must ensure that:
 * - `out_nonce` is a valid pointer with at least `len` bytes
 * - `len` is the desired length of the nonce
 */
SageResult sage_generate_nonce(unsigned char *out_nonce, size_t len);

/**
 * Clear sensitive memory
 *
 * # Safety
 * The caller must ensure that:
 * - `ptr` is a valid pointer
 * - `len` is the correct length
 */
void sage_secure_zero(unsigned char *ptr, size_t len);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* SAGE_CRYPTO_H */

/* Short aliases for the error codes used throughout the documentation. */
#define SAGE_SUCCESS SAGE_ERROR_CODE_SUCCESS
#define SAGE_ERROR_INVALID_INPUT SAGE_ERROR_CODE_INVALID_INPUT
#define SAGE_ERROR_CRYPTO SAGE_ERROR_CODE_CRYPTO_ERROR
#define SAGE_ERROR_ALLOCATION SAGE_ERROR_CODE_ALLOCATION_ERROR
#define SAGE_ERROR_UNSUPPORTED SAGE_ERROR_CODE_UNSUPPORTED
#define SAGE_ERROR_VERIFICATION_FAILED SAGE_ERROR_CODE_VERIFICATION_FAILED
#define SAGE_ERROR_UNKNOWN SAGE_ERROR_CODE_UNKNOWN_ERROR
